package com.notificationservice.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "user_info")
public class UserInfoEntity {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    //@DynamoDBAttribute
    private String toMailId;

   // @DynamoDBAttribute
    private String message;

    //@DynamoDBAttribute
    private String messageId;

   // @DynamoDBAttribute
    private String subject;

   // @DynamoDBAttribute
    private String messageSentTime;
}
